### ISSUE TITLE
Add `hello-world` exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/nix#23]
Each track must have a practice exercise named `hello-world`, which should have students just return the text `"Hello, World!"`

## Tracking

https://github.com/exercism/v3-launch/issues/34

**Comment by terlar** [comment]
This track currently has nothing. I am willing to create this, it would be my first contribution to a track, so I would have to read up a bit on how it works

**Comment by ErikSchierboom** [comment]
@terlar Great! Could you send me an email at: erik at exercism.io?

**Comment by Pamplemousse** [comment]
This seems to have been added in #48 .
