### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/nix#36]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/nix/runs/3066699484

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by kerolloz** [comment]
@ErikSchierboom 
I think it's working now
![image](https://user-images.githubusercontent.com/36763164/196004882-db6c62e1-7246-418f-8721-e456fa848130.png)
