### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by wenngle** [exercism/nix#49]
> How should we run the tests? Should we use nixpkgs lib.runTests or something like [nixt](https://github.com/nix-community/nixt/)?

_—@terlar in https://github.com/exercism/nix/issues/1#issuecomment-719135195_

This is still a relevant question. In #48, I implemented [testing](https://github.com/exercism/nix/blob/5b3ef5c864326d80ac1e1d0ad3bee582b09ffc02/exercises/practice/hello-world/hello-world-test.nix) based on `lib.debug.runTests`. This implementation is not ideal. Exercism has some [guidance](https://exercism.org/docs/building/tracks/new/select-testing-framework) on selecting a test framework.

Here are our options:
| Name | Language | Users |
| --- | --- | --- |
| [`lib.debug.runTests`](https://github.com/NixOS/nixpkgs/blob/master/lib/debug.nix#L188) | Nix | Nixpkgs |
| [nixt](https://github.com/nix-community/nixt/) | Nim + Nix | [few](https://github.com/nix-community/nixt/issues/1#issuecomment-994384624) |
| bash scripts (not really a test framework) | Bash | ubiquitous | 
| [pytest](pytest.org) (with [nix_ffi](https://github.com/nix-community/dream2nix/blob/main/src/apps/cli/nix_ffi.py)) | Python | [dream2nix](https://github.com/nix-community/dream2nix/blob/main/tests/unit) |

The command [`nix flake check`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake-check.html) provides an experimental interface to check the outputs of a flake, including tests. I don't think we should flake-ify the repo yet, though.

Nixt looks promising, but it doesn't look mature or stable enough for this project (the maintainer is in the middle of a rewrite). Most Nix projects roll their own testing, so we could develop a few utility scripts for Nix on Exercism. I don't think it's a requirement that our test framework be pure Nix.

Here are the relevant tasks:

- [ ] Choose a testing framework
- [ ] Document our choice
- [ ] Make JSON test output conform to the [test runner interface](https://exercism.org/docs/building/tooling/test-runners/interface) (nice to have)
- [ ] Automatically generate tests based on the [problem specifications](github.com/exercism/problem-specifications/) (nice to have)

I will update this issue as I investigate more.

**Comment by ErikSchierboom** [comment]
> I don't think it's a requirement that our test framework be pure Nix.

It is not, you just have to be aware that any additional dependencies make the barrier for using the track slightly higher.

**Comment by NobbZ** [comment]
> I don't think it's a requirement that our test framework be pure Nix.

There is no such requirement, the ASM track uses C, to make sure the tests are "human readable" :D

> you just have to be aware that any additional dependencies make the barrier for using the track slightly higher.

I do not think that this will be a problem for nix, as with nix each project can be made fully self-contained.

**Comment by kotp** [comment]
I think "additional dependencies" in this case can be the additional language knowledge, rather than how we might otherwise think of dependencies.

**Comment by terlar** [comment]
One tricky thing with Nix is that it has the eval part which is the Nix language itself, but we also have derivations. Should the exercises at some point involve derivations as well? In that case something like this could be useful as well:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/tests/formats.nix#L21-L32

**Comment by kotp** [comment]
For Ruby, if someone were to solve an exercise using JRuby, or mruby, or Rubinious, I would not care, even though it is not supported on the platform.  It won't hurt anything to have solutions that are not the officially supported, but having a mentor pick up if there is a specific question about a deviation from the supported version may take longer to have them pickup, or even not be available to address that, specifically.

I can imagine it being similar for any track that has variations of languages implemented.  Some being closer to the "reference implementation" than others, even.

**Comment by wenngle** [comment]
This could be relevant: https://www.tweag.io/blog/2022-09-01-unit-test-your-nix-code/. I forgot to post it when I first saw it.

> One tricky thing with Nix is that it has the eval part which is the Nix language itself, but we also have derivations. Should the exercises at some point involve derivations as well? In that case something like this could be useful as well: https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/tests/formats.nix#L21-L32

I don't think the exercises need to involve derivations. The way I understand it, derivations are something specific to Nix's use as a package manager and build system. Although they are an integral part of Nix, they're not really useful for completing the types of tasks in Exercism.

**Comment by kytrinyx** [comment]
@terlar @wenngle would you take a look at this PR? https://github.com/exercism/nix/pull/52
